version: '2.1'
services:
  registry:
    image: ${BASYX_IMAGE_NAME}:${BASYX_IMAGE_TAG}
    container_name: ${BASYX_CONTAINER_NAME}
    ports:
      - ${BASYX_HOST_PORT}:${BASYX_CONTAINER_PORT}
    depends_on:
      postgres:
        condition: service_healthy
# Possibility to embed user-configuration into the docker container 
#    volumes:
#      -  ./myConfig/myConfigs.properties:/usr/share/dockerRegistry.properties
    links:
      - postgres

  postgres:
    image: postgres:12.1
    container_name: postgres
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'admin'
      - POSTGRES_DB=basyx-directory
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 5
# Possibility to configure postgres-config into docker container
#    volumes:
#      - ./WebContent/WEB-INF/config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
#    ports:
#      - 5433:5432
#    expose:
#      - 5432
            

      